# Generated by Django 4.1.3 on 2022-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_questions_id_questions_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='num',
        ),
        migrations.AddField(
            model_name='questions',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
