# Generated by Django 4.1.3 on 2022-12-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_car_moto_delete_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.RemoveField(
            model_name='moto',
            name='user',
        ),
    ]
