# Generated by Django 4.1.3 on 2022-12-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_auto_user_remove_car_user_remove_moto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.RemoveField(
            model_name='moto',
            name='type',
        ),
    ]
